/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alotor_jvmti_NativeObject */

#ifndef _Included_alotor_jvmti_NativeObject
#define _Included_alotor_jvmti_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alotor_jvmti_NativeObject
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alotor_jvmti_NativeObject_helloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
